<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Campaign_Email.aspx.cs" Inherits="DotNet.Campaign_Email" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <asp:ScriptManager ID="ScriptManager1" runat="server" />
        <asp:UpdateProgress runat="server" ID="UpdateProgress6" class="gettext">
            <ProgressTemplate>
                <div class="loading">

                    <img src="RESOURCES/loading.gif" alt="Loading" /><br />
                </div>

            </ProgressTemplate>
        </asp:UpdateProgress>

        <div>

            <div id="EmailContent" class="container1" runat="server" hidden>
                <div class="col-12 col-s-12" id="salesreport" runat="server">
                    <asp:Label runat="server" ID="lblAutoGenerated" Font-Underline="true" Font-Bold="true" ForeColor="Red"></asp:Label><br />
                    <asp:Label ID="lblDescribes" runat="server"></asp:Label><asp:Label ID="lblDate" runat="server" Font-Bold="true"></asp:Label><br />

                </div>
            </div>
        </div>
    </form>
</body>
</html>
