using GLOBAL_FUNCTION;
using GLOBAL_VAR;
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using GLOBAL_VAR;
using System.IO;
using System.Text;
using Microsoft.Dynamics.BusinessConnectorNet;
using static QRCoder.PayloadGenerator;
using iText.StyledXmlParser.Jsoup.Nodes;

namespace DotNet
{
    public partial class Campaign_Email : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            Function_Method.isWarranty = true;
            Function_Method.isPBM = false;
            Function_Method.isPoonshReport = false;

            lblAutoGenerated.Text = SalesReport_Get_Budget.autoGen;

            NotifySalesmanCustomerReturnForm();
        }

        private void NotifySalesmanCustomerReturnForm()
        {
            MySqlConnection conn = new MySqlConnection(GLOBAL.connStr);
            DateTime CurrentDateThreeMonthsAgo = DateTime.Now.AddMonths(-3).Date;
            Dictionary<string, List<string>> CustomerDict = new Dictionary<string, List<string>>();
            conn.Open();

            string SQL = "select WorkshopName, CreatedDateTime, SalesmanID from campaign_document where CreatedDateTime <= @p0 and Status = 0";

            MySqlCommand cmd = new MySqlCommand(SQL, conn);

            cmd.Parameters.AddWithValue("@p0", CurrentDateThreeMonthsAgo);

            MySqlDataReader reader = cmd.ExecuteReader();

            while (reader.Read())
            {
                if (!CustomerDict.ContainsKey(reader.GetString("SalesmanID")))
                {
                    CustomerDict[reader.GetString("SalesmanID")] = new List<string>();
                }

                if (!string.IsNullOrEmpty(reader.GetString("SalesmanID")))
                {
                    CustomerDict[reader.GetString("SalesmanID")].Add(reader.GetString("WorkshopName"));
                }
            }

            conn.Close();

            PrepareEmailContent(CustomerDict);
        }

        private void PrepareEmailContent(Dictionary<string, List<string>> CustomerDict)
        {
            GLOBAL.switch_Company = "PPM"; GLOBAL.user_id = GLOBAL.AdminID;
            Axapta DynAx = Function_Method.GlobalAxapta();
            string HOD = "";
            string Salesman = "";
            string Content = "";

            foreach (var item in CustomerDict.Keys)
            {
                //Empltable Report to 
                int EmplTable = DynAx.GetTableIdWithLock("Empltable");
                AxaptaObject axQuery = DynAx.CreateAxaptaObject("Query");
                AxaptaObject axQueryDataSource = (AxaptaObject)axQuery.Call("addDataSource", EmplTable);

                int EmplID = DynAx.GetFieldIdWithLock(EmplTable, "EmplId");
                var qbr = (AxaptaObject)axQueryDataSource.Call("addRange", EmplID);
                qbr.Call("value", item);

                AxaptaObject axQueryRun = DynAx.CreateAxaptaObject("QueryRun", axQuery);
                if ((bool)axQueryRun.Call("next"))
                {
                    AxaptaRecord DynRec = (AxaptaRecord)axQueryRun.Call("Get", EmplTable);
                    HOD = DynRec.get_Field("ReportTo").ToString();
                    Salesman = DynRec.get_Field("DEL_Name").ToString();
                    string CustomerToNotify = string.Join(",", CustomerDict[item]);

                    Content = CampaignEmailContent(CustomerToNotify);
                    DynRec.Dispose();
                }
                axQuery.Dispose();
                axQueryDataSource.Dispose();
                axQueryRun.Dispose();

                GetEmailInfo(Salesman, "", "", HOD, "", Content);

            }
        }

        protected string CampaignEmailContent(string Customer)
        {
            var CustomerList = Customer.Split(',');
            string emailContent = "Please be informed that the following Customer did not return the Incentive Campaign Offer Form yet:";
            for (var i = 0; i < CustomerList.Count(); i++)
            {
                emailContent += "\r\n\r\nApplicant Name " + (i + 1) + ": " + CustomerList[i];
            }
            //emailContent += "\r\n\r\n\r\nThank You.";

            return emailContent;
        }

        protected void GetEmailInfo(string receiver, string hod2, string hod3, string hod4, string groupHOD, string Sendmsg)
        {
            string MailSubject;

            MailSubject = "Notify to return Incentive Campaign Offer";
            //Sendmsg = GetGridviewData(gvReportGroup);

            string MailTo = "leekx@posim.com.my";//receiver;//recipient
            Function_Method.SendMail("ppm_vppp", "Administrator", MailSubject, MailTo, /*hod4*/"" + ",", Sendmsg);
            SalesReport.Flag = true;
        }
    }
}