<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="SalesReport_PBM.aspx.cs" Inherits="DotNet.SalesReport_PBM" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <link rel="shortcut icon" href="RESOURCES/LFIB_icon.ico" />

    <link href="STYLES/xxtra_global_Content_Adjuster.css" rel="stylesheet" />
    <link href="STYLES/xtra_Full_Page_Tab.css" rel="stylesheet" />
    <link href="STYLES/xtra_Glowing.css" rel="stylesheet" />
    <link href="STYLES/xtra_Grid_View.css" rel="stylesheet" />
    <link href="STYLES/xtra_ButtonUp.css" rel="stylesheet" />
    <script src="scripts/jquery/jquery.min.js" type="text/javascript"></script>

    <title>Sales Force Automation</title>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="mobile-web-app-capable" content="yes" />
    <script src="scripts/GoToTab.js"></script>
    <script src="scripts/BrowserReload_ThroughHistory.js"></script>
</head>

<body>
    <style>
        label1 {
            color: red;
            text-underline-offset: initial;
        }
    </style>
    <form id="form1" runat="server">
        <asp:ScriptManager ID="ScriptManager1" runat="server" />
        <asp:UpdateProgress runat="server" ID="UpdateProgress6" class="gettext">
            <ProgressTemplate>
                <div class="loading">

                    <img src="RESOURCES/loading.gif" alt="Loading" /><br />
                </div>

            </ProgressTemplate>
        </asp:UpdateProgress>

        <div class="col-12 col-s-12">
            <div class="col-6 col-s-6">
                <asp:Label ID="lblStatus" runat="server" CssClass="labeltext"></asp:Label>
            </div>
            <asp:HiddenField ID="hdsalesman" runat="server" />
        </div>

        <div id="gridviewReport" class="container1" runat="server" hidden>
            <div class="col-12 col-s-12" id="salesreport" runat="server">
                <asp:Label runat="server" ID="lblAutoGenerated" Font-Underline="true" Font-Bold="true" ForeColor="Red"></asp:Label><br />
                <asp:Label ID="lblDescribes" runat="server"></asp:Label><asp:Label ID="lblDate" runat="server" Font-Bold="true"></asp:Label><br />
                <br />
                <asp:GridView ID="gvReportPBM" runat="server" HeaderStyle-CssClass="header" HorizontalAlign="Left"
                    RowStyle-CssClass="rows" Style="overflow: auto" AutoGenerateColumns="false">
                    <Columns>
                        <asp:BoundField DataField="Sales ID" HeaderText="Sales ID" ItemStyle-Width="150" HtmlEncode="false" />
                        <asp:BoundField DataField="Date Range" HeaderText="Date Range" ItemStyle-Width="250" HtmlEncode="false" />
                        <asp:BoundField DataField="Open Order (#Customer)" HeaderText="Open Order(#Customer)" ItemStyle-Width="200" HtmlEncode="false" />
                        <asp:BoundField DataField="Invoiced Sales (#Customer)" HeaderText="Invoiced Sales(#Customer)" ItemStyle-Width="200" HtmlEncode="false" />
                        <asp:BoundField DataField="Budget" HeaderText="Budget" ItemStyle-Width="200" HtmlEncode="false" />
                        <asp:BoundField DataField="Achieve Percentage(%)" HeaderText="Achieve Percentage(%)" ItemStyle-Width="200" HtmlEncode="false" />
                    </Columns>
                </asp:GridView>
                <br />
                <br />
            </div>
        </div>

    </form>
</body>
</html>