using GLOBAL_FUNCTION;
using GLOBAL_VAR;
using Microsoft.Dynamics.BusinessConnectorNet;
using System;
using System.Collections.Generic;
using System.Data;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Windows.Forms;

namespace DotNet
{
    public partial class SalesReportGroupMonthly : System.Web.UI.Page
    {
        bool isIndividual = false;
        protected void Page_Load(object sender, EventArgs e)
        {
            Function_Method.isWarranty = false;//bcc Keegan
            Function_Method.isVPPPCampaign = false;
            lblAutoGenerated.Text = SalesReport_Get_Budget.autoGen;
            string company = "PPM";

            Function_Method.isPBM = false;
            Function_Method.AddLog("PPM Group Monthly Sales Report");
            isIndividual = true;
            ExecuteByIndividual(company, SalesReport_Get_Budget.now);
            isIndividual = false;

            ExecuteByGroup(company, SalesReport_Get_Budget.now);

            lbl.Text = "PPM Monthly Sales Report completed.";
            Function_Method.AddLog("- sales report monthly email completed send out.");
        }

        protected void ExecuteByGroup(string company, DateTime now)
        {
            GLOBAL.switch_Company = company; GLOBAL.user_id = GLOBAL.AdminID;
            Axapta DynAx = Function_Method.GlobalAxapta();

            Regex regex = new Regex(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$",
                RegexOptions.CultureInvariant | RegexOptions.Singleline);
            int count = 0;

            try
            {
                var getGroupCode = SalesReport_Get_Budget.GetGroupCode(DynAx);

                for (int i = 0; i < getGroupCode.Item5; i++)//count group code
                {
                    var getEmpGroup = SalesReport_Get_Budget.getEmpDetailsFilterSalesAppGrp(DynAx, getGroupCode.Item6[i]);

                    if (!string.IsNullOrEmpty(getEmpGroup.Item6[0]) && regex.IsMatch(getEmpGroup.Item6[0]))
                    {
                        MonthlySalesReportGroup(DynAx, getGroupCode.Item6[i]);
                        Debug.WriteLine(getEmpGroup.Item6[0]);
                        var getHODemailGroup = SalesReport_Get_Budget.get_HODemplIdLvl(DynAx, getGroupCode.Item6[i]);
                        GetEmailInfo(getHODemailGroup.Item1, getHODemailGroup.Item2, getHODemailGroup.Item3, getHODemailGroup.Item4, getEmpGroup.Item7);
                        SalesReport.InsertSQL(company + " Group Monthly - " + getGroupCode.Item6[i]);
                        Function_Method.AddLog("- " + company + " Group Monthly - " + getGroupCode.Item6[i]);

                        count++;
                    }
                }
                Function_Method.AddLog("- " + count.ToString() + " " + company + " salesman group monthly email sent completed.");
            }
            catch (Exception ex)
            {
                Function_Method.AddLog("> Error: " + ex.Message);
                throw;
            }
        }

        protected void MonthlySalesReportGroup(Axapta DynAx, string approvalLvl)
        {
            DateTime now = DateTime.Now;
            var firstDayOfYear = new DateTime(now.Year, 1, 1).ToString("dd/MM/yyyy");
            var previousFirstDayOfMonth = new DateTime(now.Year, now.Month, 1).AddMonths(-1).ToString("dd/MM/yyyy");
            var lastDayOfPreviousMonth = new DateTime(now.Year, now.Month, 1).AddDays(-1).ToString("dd/MM/yyyy");

            // JJ 20245-01-15 Fixed year selection
            if (DateTime.ParseExact(firstDayOfYear, "dd/MM/yyyy", System.Globalization.CultureInfo.InvariantCulture).Year > DateTime.ParseExact(lastDayOfPreviousMonth, "dd/MM/yyyy", System.Globalization.CultureInfo.InvariantCulture).Year)
            {
                firstDayOfYear = new DateTime(DateTime.ParseExact(firstDayOfYear, "dd/MM/yyyy", System.Globalization.CultureInfo.InvariantCulture).Year - 1, 1, 1).ToString("dd/MM/yyyy");
            }
            // JJ 20245-01-15 Fixed year selection - END

            lblDescribes.Text = "Following describes the Sales Report for the following Group " + approvalLvl + " on ";
            lblDate.Text = previousFirstDayOfMonth;

            try
            {
                DataTable dt = new DataTable();
                int data_count = 5;
                string[] N = new string[data_count];

                N[0] = "Sales ID"; N[1] = "Date Range"; N[2] = "Current";
                N[3] = "Budget"; N[4] = "Achieve Percentage(%)";
                for (int i = 0; i < data_count; i++)
                {
                    dt.Columns.Add(new DataColumn(N[i], typeof(string)));
                }

                var getEmpFilterGroup = SalesReport_Get_Budget.getEmpDetailsFilterSalesAppGrp(DynAx, approvalLvl);

                List<double> totalSalesOder = new List<double>();
                List<double> totalInvoicedSales = new List<double>();
                List<double> totalInvoiceSalesYTD = new List<double>();
                List<double> totalBudget = new List<double>();
                List<double> totalBudgetYTD = new List<double>();

                DataRow row;
                int countCurrent = 0;
                for (int i = 0; i < getEmpFilterGroup.Item5; i++)
                {
                    double calPercentage = 0; double calPercentageYTD = 0;

                    var tuple_get_CurrentMonthTotal = SFA_GET_Enquiries_SalesmanTotal.get_ITotal_TableRun_s
                        (DynAx, getEmpFilterGroup.Item4[i], previousFirstDayOfMonth, lastDayOfPreviousMonth);

                    string monthlyPeriodName = SalesReport_Get_Budget.getStartDateToDate(DynAx, lastDayOfPreviousMonth);
                    if (string.IsNullOrEmpty(monthlyPeriodName))
                    {
                        monthlyPeriodName = "-";//assign - to avoid getting wrong periodname in salesbudget
                    }
                    var monthlyBudget = SalesReport_Get_Budget.getPeriodName(DynAx, monthlyPeriodName, getEmpFilterGroup.Item4[i]);

                    var yearlyPeriodName = SalesReport_Get_Budget.getStartDateToDateYearly(DynAx, lastDayOfPreviousMonth);
                    double yearlyBudget = SalesReport_Get_Budget.getPeriodNameYearlyForMonthlyReport(DynAx, yearlyPeriodName.Item2, yearlyPeriodName.Item3, getEmpFilterGroup.Item4[i]);

                    var get_Total = SFA_GET_Enquiries_SalesmanTotal.getTotal(DynAx, getEmpFilterGroup.Item4[i], firstDayOfYear, lastDayOfPreviousMonth);
                    double totalAmount = get_Total.Item1;

                    row = dt.NewRow();
                    row["Sales ID"] = getEmpFilterGroup.Item4[i] + " " + getEmpFilterGroup.Item1[i];
                    row["Date Range"] = previousFirstDayOfMonth + " - " + lastDayOfPreviousMonth + "<br>" + "<br>" + firstDayOfYear + " - " + lastDayOfPreviousMonth;
                    row["Current"] = tuple_get_CurrentMonthTotal.Item1.ToString("#,###,###,##0") + " (" + tuple_get_CurrentMonthTotal.Item4 + ")" +
                                         "<br>" + "<br>" + totalAmount.ToString("#,###,###,##0") + " (" + get_Total.Item2 + ")";
                    totalInvoicedSales.Add(tuple_get_CurrentMonthTotal.Item1);
                    totalInvoiceSalesYTD.Add(totalAmount);
                    countCurrent = countCurrent + get_Total.Item2;

                    row["Budget"] = monthlyBudget.Item1.ToString("#,###,###,##0") + "<br>" + "<br>" + yearlyBudget.ToString("#,###,###,##0");
                    totalBudget.Add(monthlyBudget.Item1);
                    totalBudgetYTD.Add(yearlyBudget);

                    if (tuple_get_CurrentMonthTotal.Item1 != 0 && monthlyBudget.Item1 != 0)
                    {
                        calPercentage = tuple_get_CurrentMonthTotal.Item1 / monthlyBudget.Item1 * 100;
                    }

                    if (totalAmount != 0 && yearlyBudget != 0)
                    {
                        calPercentageYTD = totalAmount / yearlyBudget * 100;
                    }

                    row["Achieve Percentage(%)"] = calPercentage.ToString("N2") + "<br>" + "<br>" + calPercentageYTD.ToString("N2");
                    dt.Rows.Add(row);
                }

                row = dt.NewRow();
                double calTotalPercentage = 0; double calTotalPercentageYTD = 0;

                row["Sales ID"] = "Total";
                row["Date Range"] = previousFirstDayOfMonth + " - " + lastDayOfPreviousMonth + "<br>" + firstDayOfYear + " - " + lastDayOfPreviousMonth;

                double getInvoiceSales = totalInvoicedSales.Sum();
                double getTotalInvoiceSalesYTD = totalInvoiceSalesYTD.Sum();
                row["Current"] = getInvoiceSales.ToString("#,###,###,##0") + "<br>" + getTotalInvoiceSalesYTD.ToString("#,###,###,##0");

                double getTotalBudget = totalBudget.Sum();
                double getTotalBudgetYTD = totalBudgetYTD.Sum();
                row["Budget"] = getTotalBudget.ToString("#,###,###,##0") + "<br>" + getTotalBudgetYTD.ToString("#,###,###,##0");
                if (getTotalBudget != 0)
                {
                    calTotalPercentage = getInvoiceSales / getTotalBudget * 100;
                }

                if (getTotalBudgetYTD != 0 && getTotalInvoiceSalesYTD != 0)
                {
                    calTotalPercentageYTD = getTotalInvoiceSalesYTD / getTotalBudgetYTD * 100;
                }

                row["Achieve Percentage(%)"] = calTotalPercentage.ToString("N2") + "<br>" + "<br>" + calTotalPercentageYTD.ToString("N2");

                dt.Rows.Add(row);
                gvReportGroup.DataSource = dt;
                gvReportGroup.DataBind();

                int row_count = gvReportGroup.Rows.Count;
                string[] result; string[] delim = { "<br><br>" };
                for (int i = 0; i < row_count; i++)
                {
                    string percentage = gvReportGroup.Rows[i].Cells[4].Text;
                    //Debug.WriteLine(percentage);
                    result = percentage.Split(delim, StringSplitOptions.None);
                    if (Convert.ToDouble(result[0]) < 50)
                    {
                        gvReportGroup.Rows[i].Cells[4].Text = "<span style='color:red'>" + result[0] + "</span><br><br>" + result[1];

                        if (Convert.ToDouble(result[1]) < 50)
                        {
                            gvReportGroup.Rows[i].Cells[4].Text = "<span style='color:red'>" + result[0] + "<br><br><span style='color:red'>" + result[1] + "</span>";
                        }
                    }//change textcolor to red when percentage is not below 50
                    else if (Convert.ToDouble(result[1]) < 50)
                    {
                        gvReportGroup.Rows[i].Cells[4].Text = result[0] + "<br><br><span style='color:red'>" + result[1] + "</span>";
                    }
                }
            }
            catch (Exception)
            {
                throw;
            }
        }

        private void ExecuteByIndividual(string company, DateTime now)
        {
            gvReport.DataSource = null;
            gvReport.DataBind();
            GLOBAL.switch_Company = company; GLOBAL.user_id = GLOBAL.AdminID;
            Axapta DynAx = Function_Method.GlobalAxapta();

            string salesmanID = ""; string temp_email = ""; int count = 0;
            try
            {
                List<ListItem> items = new List<ListItem>();
                List<string> email = new List<string>();
                items = SalesReport_Get_Budget.getSalesman(DynAx);
                for (int i = 0; i < items.Count; i++)
                {
                    Regex regex = new Regex(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$",
                        RegexOptions.CultureInvariant | RegexOptions.Singleline);

                    var salesman = items[i];
                    salesmanID = salesman.Value;
                    var getEmplDetails = SalesReport_Get_Budget.getEmpDetails(DynAx, salesmanID);
                    hdsalesman.Value = getEmplDetails.Item1;

                    var getEmail = SalesReport_Get_Budget.getEmpDetails2(DynAx, getEmplDetails.Item6);

                    if (temp_email != getEmplDetails.Item6 && !string.IsNullOrEmpty(getEmail.Item5[0]))// check salesman second account/check email is empty or not
                    {
                        if (regex.IsMatch(getEmail.Item5[0]) && !email.Contains(getEmplDetails.Item6))// validate email/check for existed email
                        {
                            email.Add(getEmplDetails.Item6);//store first email
                            MonthlySalesReportByIndividual(DynAx, salesmanID);
                            temp_email = getEmplDetails.Item6;//set it to temp for second account checking purposes
                            Debug.WriteLine(salesmanID);
                            //var empDetails = SalesReport_Get_Budget.getEmpDetails(DynAx, salesmanID);

                            var getHODemail = SalesReport_Get_Budget.get_HODemplIdLvl(DynAx, getEmplDetails.Item7.ToString());
                            if (SalesReport_Get_Budget.getSkipHODstatus(DynAx, salesmanID) == "1")
                            {
                                GetEmailInfo(getEmplDetails.Item6, "", "", "", hdsalesman.Value);
                                Function_Method.AddLog("- " + company + " skip HOD" + getEmplDetails.Item6);
                            }
                            else
                            {
                                GetEmailInfo(getEmplDetails.Item6, getHODemail.Item1, getHODemail.Item2, getHODemail.Item3, hdsalesman.Value);
                            }
                            SalesReport.InsertSQL(company + " " + getEmplDetails.Item6);
                            Function_Method.AddLog("- " + company + " " + getEmplDetails.Item6);

                            gvReport.Dispose();
                            count++;

                        }
                    }
                    regex = null;
                    getEmplDetails = null;
                    getEmail = null;
                }
                Function_Method.AddLog("- " + count.ToString() + " " + company + " individual monthly email sent completed.");
            }
            catch (Exception ex)
            {
                Function_Method.AddLog("> Error: " + ex.Message);
                throw;
            }
            finally
            {
                DynAx.Dispose();
            }
        }

        protected void MonthlySalesReportByIndividual(Axapta DynAx, string SalesmanID)
        {
            DateTime now = DateTime.Now;
            var firstDayOfYear = new DateTime(now.Year, 1, 1).ToString("dd/MM/yyyy");
            var previousFirstDayOfMonth = new DateTime(now.Year, now.Month, 1).AddMonths(-1).ToString("dd/MM/yyyy");
            var lastDayOfPreviousMonth = new DateTime(now.Year, now.Month, 1).AddDays(-1).ToString("dd/MM/yyyy");

            // JJ 2025-01-15 Fixed year selection
            if (DateTime.ParseExact(firstDayOfYear, "dd/MM/yyyy", System.Globalization.CultureInfo.InvariantCulture).Year > DateTime.ParseExact(lastDayOfPreviousMonth, "dd/MM/yyyy", System.Globalization.CultureInfo.InvariantCulture).Year)
            {
                firstDayOfYear = new DateTime(DateTime.ParseExact(firstDayOfYear, "dd/MM/yyyy", System.Globalization.CultureInfo.InvariantCulture).Year - 1, 1, 1).ToString("dd/MM/yyyy");
            }
            // JJ 2025-01-15 Fixed year selection - END

            lblDescribes.Text = "Following describes the Sales Report for the following Salesman ID " + SalesmanID + " on ";
            lblDate.Text = previousFirstDayOfMonth;

            try
            {
                DataTable dt = new DataTable();
                int data_count = 6;
                string[] N = new string[data_count];

                N[0] = "Sales ID"; N[1] = "Date Range"; N[2] = "Open Order (#Customer)";
                N[3] = "Invoiced Sales (#Customer)"; N[4] = "Budget"; N[5] = "Achieve Percentage(%)";
                for (int i = 0; i < data_count; i++)
                {
                    dt.Columns.Add(new DataColumn(N[i], typeof(string)));
                }

                var getEmplDetails = SalesReport_Get_Budget.getEmpDetails(DynAx, SalesmanID);
                var getEmail = SalesReport_Get_Budget.getEmpDetails2(DynAx, getEmplDetails.Item6);

                List<double> totalSalesOrder = new List<double>();
                List<double> sumSalesOrder = new List<double>();
                List<double> totalInvoicedSales = new List<double>();
                List<double> totalInvoiceSalesYTD = new List<double>();
                List<double> totalBudget = new List<double>();
                List<double> totalBudgetYTD = new List<double>();

                DataRow row;
                //int OpenOrder = 0; int invoiceSales = 0;
                int getCustomerOpenOrder = 0;
                string monthlyPeriodName = SalesReport_Get_Budget.getStartDateToDate(DynAx, lastDayOfPreviousMonth);

                for (int i = 0; i < getEmail.Item4; i++)//count salesman email
                {
                    double calPercentage = 0; double calPercentageYTD = 0;

                    var tuple_get_CurrentMonthTotal = SFA_GET_Enquiries_SalesmanTotal.get_ITotal_TableRun_s
                        (DynAx, getEmail.Item3[i], previousFirstDayOfMonth, lastDayOfPreviousMonth);

                    var monthlyBudget = SalesReport_Get_Budget.getPeriodName(DynAx, monthlyPeriodName, getEmail.Item3[i]);

                    var yearlyPeriodName = SalesReport_Get_Budget.getStartDateToDateYearly(DynAx, lastDayOfPreviousMonth);
                    double yearlyBudget = SalesReport_Get_Budget.getPeriodNameYearlyForMonthlyReport(DynAx, yearlyPeriodName.Item2, yearlyPeriodName.Item3, getEmail.Item3[i]);

                    var get_Total = SFA_GET_Enquiries_SalesmanTotal.getTotal(DynAx, getEmail.Item3[i], firstDayOfYear, lastDayOfPreviousMonth);
                    double totalAmount = get_Total.Item1;

                    var getCustAcc = Payment_GET_Ledger_Journal_Table.get_CustTable(DynAx, getEmail.Item3[i]);

                    row = dt.NewRow();
                    row["Sales ID"] = getEmail.Item3[i];
                    row["Date Range"] = previousFirstDayOfMonth + " - " + lastDayOfPreviousMonth + "<br>" + "<br>" + firstDayOfYear + " - " + lastDayOfPreviousMonth;
                    row["Open Order (#Customer)"] = "<br>" + "<br>" + "0" + " (" + "0" + ")";
                    totalSalesOrder.Clear();
                    int count = 0;
                    for (int j = 0; j < getCustAcc.Item3; j++)
                    {
                        var invoiceSalesMonthly = SalesReport_Get_Budget.getSalesOrder(DynAx, getCustAcc.Item1[j], firstDayOfYear, lastDayOfPreviousMonth);
                        totalSalesOrder.Add(invoiceSalesMonthly.Item1);
                        if (invoiceSalesMonthly.Item2 != 0)
                        {
                            count++;
                            row["Open Order (#Customer)"] = "<br>" + "<br>" + totalSalesOrder.Sum().ToString("N0") + " (" + count + ")";
                            getCustomerOpenOrder = invoiceSalesMonthly.Item2;
                        }
                    }
                    //OpenOrder = OpenOrder + getCustomerOpenOrder;//count customer of open order
                    sumSalesOrder.Add(totalSalesOrder.Sum());

                    row["Invoiced Sales (#Customer)"] = tuple_get_CurrentMonthTotal.Item1.ToString("#,###,###,##0") + " (" + tuple_get_CurrentMonthTotal.Item4 + ")" +
                                         "<br>" + "<br>" + totalAmount.ToString("#,###,###,##0") + " (" + get_Total.Item2 + ")";
                    totalInvoicedSales.Add(tuple_get_CurrentMonthTotal.Item1);
                    totalInvoiceSalesYTD.Add(totalAmount);
                    //invoiceSales = invoiceSales + tuple_get_CurrentMonthTotal.Item4;//count customer of invoice sales

                    row["Budget"] = monthlyBudget.Item1.ToString("#,###,###,##0") + "<br>" + "<br>" + yearlyBudget.ToString("#,###,###,##0");
                    totalBudget.Add(monthlyBudget.Item1);
                    totalBudgetYTD.Add(yearlyBudget);

                    if (tuple_get_CurrentMonthTotal.Item1 != 0 && monthlyBudget.Item1 != 0)
                    {
                        calPercentage = tuple_get_CurrentMonthTotal.Item1 / monthlyBudget.Item1 * 100;
                    }

                    if (totalAmount != 0 && yearlyBudget != 0)
                    {
                        calPercentageYTD = totalAmount / yearlyBudget * 100;
                    }

                    row["Achieve Percentage(%)"] = calPercentage.ToString("N2") + "<br>" + "<br>" + calPercentageYTD.ToString("N2");
                    dt.Rows.Add(row);
                }

                row = dt.NewRow();
                double getTotalAP = 0; double getTotalApYTD = 0;

                row["Sales ID"] = "Total";
                row["Date Range"] = previousFirstDayOfMonth + " - " + lastDayOfPreviousMonth + "<br>" + "<br>" + firstDayOfYear + " - " + lastDayOfPreviousMonth;
                row["Open Order (#Customer)"] = "<br>" + "<br>" + sumSalesOrder.Sum().ToString("#,###,###,##0");

                double getInvoiceSales = totalInvoicedSales.Sum();
                double getTotalInvoiceSalesYTD = totalInvoiceSalesYTD.Sum();
                row["Invoiced Sales (#Customer)"] = getInvoiceSales.ToString("#,###,###,##0") + "<br>" + "<br>" +
                                        getTotalInvoiceSalesYTD.ToString("#,###,###,##0");

                double getTotalBudget = totalBudget.Sum();
                double getTotalBudgetYTD = totalBudgetYTD.Sum();
                row["Budget"] = getTotalBudget.ToString("#,###,###,##0") + "<br>" + "<br>" + getTotalBudgetYTD.ToString("#,###,###,##0");
                if (getTotalBudget != 0)
                {
                    getTotalAP = getInvoiceSales / getTotalBudget * 100;
                }

                if (getTotalBudgetYTD != 0 && getTotalInvoiceSalesYTD != 0)
                {
                    getTotalApYTD = getTotalInvoiceSalesYTD / getTotalBudgetYTD * 100;
                }

                row["Achieve Percentage(%)"] = getTotalAP.ToString("N2") + "<br>" + "<br>" + getTotalApYTD.ToString("N2");

                dt.Rows.Add(row);
                gvReport.DataSource = dt;
                gvReport.DataBind();

                int row_count = gvReport.Rows.Count;
                string[] result; string[] delim = { "<br><br>" };
                for (int i = 0; i < row_count; i++)
                {
                    string percentage = gvReport.Rows[i].Cells[5].Text;
                    //Debug.WriteLine(percentage);
                    result = percentage.Split(delim, StringSplitOptions.None);
                    if (Convert.ToDouble(result[0]) < 50)
                    {
                        gvReport.Rows[i].Cells[5].Text = "<span style='color:red'>" + result[0] + "</span><br><br>" + result[1];

                        if (Convert.ToDouble(result[1]) < 50)
                        {
                            gvReport.Rows[i].Cells[5].Text = "<span style='color:red'>" + result[0] + "<br><br><span style='color:red'>" + result[1] + "</span>";
                        }
                    }//change textcolor to red when percentage is not below 50
                    else if (Convert.ToDouble(result[1]) < 50)
                    {
                        gvReport.Rows[i].Cells[5].Text = result[0] + "<br><br><span style='color:red'>" + result[1] + "</span>";
                    }
                }
            }
            catch (Exception)
            {
                throw;
            }
        }

        protected string GetGridviewData(GridView gv)
        {
            StringBuilder strBuilder = new StringBuilder();
            StringWriter strWriter = new StringWriter(strBuilder);
            HtmlTextWriter htw = new HtmlTextWriter(strWriter);
            gridviewReport.RenderControl(htw);

            return strBuilder.ToString();
        }

        protected void GetEmailInfo(string receiver, string hod2, string hod3, string hod4, string groupHOD)
        {
            string MailSubject; string Sendmsg = "";

            if (isIndividual)
            {
                MailSubject = "MTD Sales Report for " + groupHOD;

                Sendmsg = GetGridviewData(gvReport);
            }
            else
            {
                gvReport.Visible = false;
                MailSubject = "MTD Sales Report for Group " + groupHOD;

                Sendmsg = GetGridviewData(gvReportGroup);
            }
            string MailTo = receiver;//recipient
            Function_Method.SendMail("mailadmin", "Administrator", MailSubject, MailTo, hod2 + "," + hod3 + "," + hod4, Sendmsg);
            SalesReport.Flag = true;
        }

        public override void VerifyRenderingInServerForm(System.Web.UI.Control control)
        {
            /* Verifies that the control is rendered */
        }

    }
}