<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="SalesReport_OtherDiv.aspx.cs" Inherits="DotNet.SalesReport_OtherDiv" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <link rel="shortcut icon" href="RESOURCES/LFIB_icon.ico" />

    <link href="STYLES/xxtra_global_Content_Adjuster.css" rel="stylesheet" />
    <link href="STYLES/xtra_Full_Page_Tab.css" rel="stylesheet" />
    <link href="STYLES/xtra_Glowing.css" rel="stylesheet" />
    <link href="STYLES/xtra_Grid_View.css" rel="stylesheet" />
    <link href="STYLES/xtra_ButtonUp.css" rel="stylesheet" />
    <script src="scripts/jquery/jquery.min.js" type="text/javascript"></script>

    <title>Sales Force Automation</title>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="mobile-web-app-capable" content="yes" />
    <script src="scripts/GoToTab.js"></script>
    <script src="scripts/BrowserReload_ThroughHistory.js"></script>
</head>

<body>
    <style>
        label1 {
            color: red;
            text-underline-offset: initial;
        }
    </style>
    <form id="form1" runat="server">
        <asp:ScriptManager ID="ScriptManager1" runat="server" />
        <asp:UpdateProgress runat="server" ID="UpdateProgress6" class="gettext" AssociatedUpdatePanelID="UpdatePanel6">
            <ProgressTemplate>
                <div class="loading">

                    <img src="RESOURCES/loading.gif" alt="Loading" /><br />
                </div>

            </ProgressTemplate>
        </asp:UpdateProgress>

        <asp:UpdatePanel ID="UpdatePanel6" runat="server">
            <ContentTemplate>

                <div class="col-6 col-s-12">
                    <div class="col-3 col-s-4">
                        <label class="labeltext" hidden>Salesman:      </label>
                    </div>
                    <div class="col-3 col-s-8">
                        <asp:DropDownList ID="DropDownList2" runat="server" class="dropdownlist" AutoPostBack="true" Visible="false">
                        </asp:DropDownList>
                    </div>
                </div>

                <div class="col-12 col-s-12">
                    <div class="col-6 col-s-6">
                        <asp:Label ID="lblStatus" runat="server" CssClass="labeltext"></asp:Label>
                    </div>
                    <asp:HiddenField ID="hdsalesman" runat="server" />
                </div>

                <div id="gridviewReport" class="container1" runat="server">
                    <div class="col-12 col-s-12" id="salesreport" runat="server">
                        <asp:Label runat="server" ID="lblAutoGenerated" Font-Underline="true" ForeColor="Red"></asp:Label><br />
                        <asp:Label ID="lblDescription" runat="server"></asp:Label><asp:Label ID="lblDate" runat="server"></asp:Label><br />
                        <br />

                        <asp:Label ID="lblPercentage" runat="server" Text="Percentage (%)" Font-Bold="true"></asp:Label><br />
                        <asp:Label ID="lblGetPercentage" runat="server"></asp:Label><br />
                        <br />

                        <asp:Label ID="lblDtRange" runat="server" Text="Date Range" Font-Bold="true"></asp:Label><br />
                        <asp:Label ID="lblGetDtRange" runat="server"></asp:Label><br />
                        <br />

                        <asp:Label ID="lblSalesOrder" runat="server" Text="Sales Order" Font-Bold="true"></asp:Label><br />
                        <asp:Label ID="lblGetSalesOrder" runat="server"></asp:Label><br />
                        <br />

                        <asp:Label ID="lblInvoiceSales" runat="server" Text="Invoiced Sales" Font-Bold="true"></asp:Label><br />
                        <asp:Label ID="lblGetInvoiceSales" runat="server"></asp:Label><br />
                        <br />

                        <asp:Label ID="lblBudget" runat="server" Text="Budget" Font-Bold="true"></asp:Label><br />
                        <asp:Label ID="lblGetBudget" runat="server"></asp:Label><br />
                        <br />

                    </div>
                </div>
            </ContentTemplate>

        </asp:UpdatePanel>
    </form>
</body>
</html>